export const tableOption = {
    "border": true,
    "index": true,
    "indexLabel": "序号",
    "stripe": true,
    "menuAlign": "center",
    "align": "center",
    "dialogDirection": "rtl",
    "searchMenuSpan": 6,
    "column": [
        {
            "type": "input",
            "label": "",
            "prop": "id"
        }, {
            "type": "input",
            "label": "信息标题",
            "prop": "name"
        }, {
            "type": "input",
            "label": "村id",
            "prop": "did"
        }, {
            "type": "input",
            "label": "村组id",
            "prop": "dsid"
        }, {
            "type": "input",
            "label": "年",
            "prop": "year"
        }, {
            "type": "input",
            "label": "月",
            "prop": "month"
        }, {
            "type": "input",
            "label": "日",
            "prop": "day"
        }, {
            "type": "input",
            "label": "类型",
            "prop": "type"
        }, {
            "type": "input",
            "label": "是否显示：1-显示，0-不显示",
            "prop": "state"
        }, {
            "type": "input",
            "label": "内容",
            "prop": "content"
        }, {
            "type": "input",
            "label": "关联id",
            "prop": "linkid"
        }, {
            "type": "input",
            "label": "排序",
            "prop": "sort"
        }, {
            "type": "input",
            "label": "创建时间",
            "prop": "createTime"
        }, {
            "type": "input",
            "label": "修改时间",
            "prop": "updateTime"
        }, {
            "type": "input",
            "label": "是否删除  -1：已删除  0：正常",
            "prop": "delFlag"
        }, {
            "type": "input",
            "label": "管理端创建人",
            "prop": "createBy"
        }, {
            "type": "input",
            "label": "发布时间",
            "prop": "publishTime"
        }]
}
